// Mocks generated by Mockito 5.4.4 from annotations
// in lista_de_tareas/test/provides/porvider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:lista_de_tareas/models/model_tarea.dart' as _i2;
import 'package:lista_de_tareas/services/api_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTarea_0 extends _i1.SmartFake implements _i2.Tarea {
  _FakeTarea_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  _i5.Future<List<_i2.Tarea>> getTareas() => (super.noSuchMethod(
        Invocation.method(
          #getTareas,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Tarea>>.value(<_i2.Tarea>[]),
      ) as _i5.Future<List<_i2.Tarea>>);

  @override
  _i5.Future<_i2.Tarea> createTarea(_i2.Tarea? tarea) => (super.noSuchMethod(
        Invocation.method(
          #createTarea,
          [tarea],
        ),
        returnValue: _i5.Future<_i2.Tarea>.value(_FakeTarea_0(
          this,
          Invocation.method(
            #createTarea,
            [tarea],
          ),
        )),
      ) as _i5.Future<_i2.Tarea>);

  @override
  _i5.Future<_i2.Tarea> updateTarea(_i2.Tarea? tarea) => (super.noSuchMethod(
        Invocation.method(
          #updateTarea,
          [tarea],
        ),
        returnValue: _i5.Future<_i2.Tarea>.value(_FakeTarea_0(
          this,
          Invocation.method(
            #updateTarea,
            [tarea],
          ),
        )),
      ) as _i5.Future<_i2.Tarea>);

  @override
  _i5.Future<void> deleteTarea(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteTarea,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
